# ================ EasyBackUp插件配置 ================
# 说明: 此插件用于定时备份 Minecraft 服务器的重要数据
# 作者: WilliamPepsi66
# 版本: v1.0

# 备份间隔时间（单位：小时）
# 默认: 6 (每6小时备份一次)
# 注意: 设置为 0 可禁用自动备份
backup-interval-hours: 6

# 需要备份的目录列表（相对于服务器根目录）
# 重要提示:
#   - 路径区分大小写！
#   - 子目录会自动包含，无需单独列出
target-save-dir:
  - 'world'

# 最大备份保留数量（防止磁盘占满）
# 默认: 10 (超过数量时自动删除最旧的备份)
max-backups: 10

# 备份时是否显示服务器广播消息
# 默认: true
# 期望: true/false
notify-players: true